project_id = "mxrjsclpdwmrrvmzmqmo"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
port = 54324
external_url = "https://mxrjsclpdwmrrvmzmqmo.supabase.co"

[functions.ocr]
verify_jwt = true

[functions.send-email]
verify_jwt = false

[functions.reports]
verify_jwt = true

[functions.dev-seed]
verify_jwt = true

[functions.run-rollups]
verify_jwt = true