// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mxrjsclpdwmrrvmzmqmo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im14cmpzY2xwZHdtcnJ2bXptcW1vIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQzODYzMTIsImV4cCI6MjA2OTk2MjMxMn0.GPD_SYgcmCTHokdzUMV-mGqMvDd5LK-KQH9pjhd8UoY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});